### ISSUE TITLE
BOJ 1019 풀이

### ISSUE THREAD

**Issue by mjy9088** [developers-algorithm-study/yeoptti#1]
[BOJ 1019](https://www.acmicpc.net/problem/1019) 제출 안 하셨죠? ㅠㅠ

그렇게 쉬운 문제가 아니었는데!!!

**Comment by inyeoptti** [comment]
아직 안풀었다구욧!

**Comment by mjy9088** [comment]
아하 그렇군요.

이제 문제 풀고 이슈 닫으시면 될 듯! (?)
